permalink: /:year:month:day/:title
url: https://the.riturajps.in
baseurl: /

# variables
name: Ritu Raj Pratap Singh
description: IT professional in final year, skilled in SQL, web development, programming (C, C++, Java), and OS security. Experienced blogger simplifying IT concepts with hands-on expertise in Linux and OS Architecture.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true