# Site Build Settings

# jekyll-paginate configuration
paginate:            8

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /blog/:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           'Ritu Raj’s Blog'
tagline:             'From Ideas to Execution'
description:	       'At Ritu Raj’s Blog, we help you turn your ideas into reality. Whether you’re learning new skills, building projects, or exploring tech, our easy guides and tools are here to support your journey every step of the way.'
author:              'Ritu Raj Pratap Singh'

twitter:
  username: riturajps

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
# feed:
#  path: rss-feed.xml